version: "3"

services:
    server:
        container_name: "server"
        build: .
        entrypoint: php artisan serve --host 0.0.0.0
        volumes:
            - .:/var/www
        ports:
            - "8080:8000"
        networks:
            - server
        depends_on:
            - db
    db:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: db
            MYSQL_USER: db
            MYSQL_ROOT_PASSWORD: db
        networks:
            - server

networks:
    server:
